# Generated by Django 5.1 on 2024-11-03 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_study_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.study"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "스터디 참가 이력",
                "db_table": "study_participation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("study", "user"), name="study_participation"
                    )
                ],
            },
        ),
    ]
