# Generated by Django 5.1 on 2024-11-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_study_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="학생 이름")),
                (
                    "student_number",
                    models.CharField(max_length=128, verbose_name="학번"),
                ),
                (
                    "primary_major",
                    models.CharField(max_length=128, verbose_name="제 1전공"),
                ),
            ],
        ),
    ]
